### ISSUE TITLE
Passing contexts

### ISSUE THREAD

**Issue by cxkoda** [JulianToledano/goingecko#25]
I think ideally all endpoint methods should take in [contexts](https://pkg.go.dev/context) so the underling calls to the coingecko API are properly cancelled if the parent context dies. This is particularly helpful when one has to manage multiple calls, specifying timeouts, etc. 

Happy to submit a PR for this, but wanted to discuss it first since it's a bit of a larger change and breaks backwards compatibility if we just add it to the existing methods.

**Comment by JulianToledano** [comment]
yes, it makes all the sense. Don't worry about breaking changes. I have in mind to do some more
